server:
  port: 8083

spring:
  application:
    name: rating-service
  datasource:
    url: jdbc:mysql://localhost:3306/microservices_ratingService
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  config:
    import: optional:configserver:http://localhost:8085

#will get fetch from config-server
#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    fetch-registry: true
#    registry-with-eureka: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka

okta:
  oauth2:
    issuer: https://dev-46616172.okta.com/oauth2/default
    audience: api://default